### ISSUE TITLE
lib/platform.js is missing

### ISSUE THREAD

**Issue by petebacondarwin** [angular/projects#5]
I run 

```
gulp build serve
```

and then access `localhost:8000` and the app fails with a 404 on `lib/platform.js`.

Should I retrieve this from somewhere?

**Comment by tbosch** [comment]
Did you do bower install?

Sent from my iPhone

On Jun 26, 2014, at 5:50 AM, Pete Bacon Darwin notifications@github.com
wrote:

I run

gulp build serve

and then access localhost:8000 and the app fails with a 4040 on
lib/platform.js.

Should I retrieve this from somewhere?

—
Reply to this email directly or view it on GitHub
https://github.com/angular/projects/issues/5.

**Comment by petebacondarwin** [comment]
Ah right. Probably not

**Comment by petebacondarwin** [comment]
That was it. Sorry!
